Repository ChaseBENNC9/GameJam-Charika, pull requests merged in 2024-03, with the labels that each got.

#7 Parallax Effect Background
  AI Game Jam/Assets/Materials.meta
  AI Game Jam/Assets/Materials/Layer1Mat.mat
  AI Game Jam/Assets/Materials/Layer1Mat.mat.meta
  AI Game Jam/Assets/Materials/Layer2Mat.mat
  AI Game Jam/Assets/Materials/Layer2Mat.mat.meta
  AI Game Jam/Assets/Materials/Layer3Mat.mat
  AI Game Jam/Assets/Materials/Layer3Mat.mat.meta
  AI Game Jam/Assets/Scenes/ParallaxBGScene.unity
  AI Game Jam/Assets/Scenes/ParallaxBGScene.unity.meta
  AI Game Jam/Assets/Scripts.meta
  AI Game Jam/Assets/Scripts/ParallaxEffect.cs
  AI Game Jam/Assets/Scripts/ParallaxEffect.cs.meta
  AI Game Jam/ProjectSettings/SceneTemplateSettings.json
Labels: New Feature

#8 Release v0.1
  AI Game Jam/.vscode/extensions.json
  AI Game Jam/.vscode/launch.json
  AI Game Jam/.vscode/settings.json
  AI Game Jam/.vsconfig
  AI Game Jam/Assets/Materials.meta
  AI Game Jam/Assets/Materials/Layer1Mat.mat
  AI Game Jam/Assets/Materials/Layer1Mat.mat.meta
  AI Game Jam/Assets/Materials/Layer2Mat.mat
  AI Game Jam/Assets/Materials/Layer2Mat.mat.meta
  AI Game Jam/Assets/Materials/Layer3Mat.mat
  AI Game Jam/Assets/Materials/Layer3Mat.mat.meta
  AI Game Jam/Assets/Materials/PlayerGreen.mat
  AI Game Jam/Assets/Materials/PlayerGreen.mat.meta
  AI Game Jam/Assets/Prefabs.meta
  AI Game Jam/Assets/Prefabs/Player.prefab
  AI Game Jam/Assets/Prefabs/Player.prefab.meta
  AI Game Jam/Assets/Scenes/Level1.unity
  AI Game Jam/Assets/Scenes/Level1.unity.meta
  AI Game Jam/Assets/Scenes/SampleScene.unity
  AI Game Jam/Assets/Scripts.meta
  AI Game Jam/Assets/Scripts/CameraFollow.cs
  AI Game Jam/Assets/Scripts/CameraFollow.cs.meta
  AI Game Jam/Assets/Scripts/ParallaxEffect.cs
  AI Game Jam/Assets/Scripts/ParallaxEffect.cs.meta
  AI Game Jam/Assets/Scripts/PlayerMovement.cs
  AI Game Jam/Assets/Scripts/PlayerMovement.cs.meta
  AI Game Jam/ProjectSettings/SceneTemplateSettings.json
  AI Game Jam/ProjectSettings/TagManager.asset
  README.md
Labels: Release

#12 Jumping
  AI Game Jam/Assets/Prefabs/Player.prefab
  AI Game Jam/Assets/Scripts/CameraFollow.cs
  AI Game Jam/Assets/Scripts/PlayerMovement.cs
Labels: New Feature

#16 Pick up Items
  AI Game Jam/Assets/Scenes/PickupItems.unity
  AI Game Jam/Assets/Scenes/PickupItems.unity.meta
  AI Game Jam/Assets/Scripts/PickupItem.cs
  AI Game Jam/Assets/Scripts/PickupItem.cs.meta
  AI Game Jam/Assets/Scripts/PlayerMovement.cs
  AI Game Jam/ProjectSettings/TagManager.asset
Labels: New Feature

#26 Security Light
  AI Game Jam/Assets/Scenes/SecurityLight.unity
  AI Game Jam/Assets/Scenes/SecurityLight.unity.meta
  AI Game Jam/Assets/Scripts/SecurityLight.cs
  AI Game Jam/Assets/Scripts/SecurityLight.cs.meta
  AI Game Jam/Assets/Scripts/SecurityLightMovement.cs
  AI Game Jam/Assets/Scripts/SecurityLightMovement.cs.meta
Labels: New Feature

#34 Prologue Security Lights
  AI Game Jam/Assets/Prefabs/Security Light.prefab
  AI Game Jam/Assets/Prefabs/Security Light.prefab.meta
  AI Game Jam/Assets/Scenes/Prologue.unity
  AI Game Jam/Assets/Scenes/SecurityLight.unity
  AI Game Jam/Assets/Scripts/SecurityLightMovement.cs
Labels: Expanded Feature

#36 Complex Puzzle
  AI Game Jam/Assets/Materials/Darker Gray 1.mat
  AI Game Jam/Assets/Materials/Darker Gray 1.mat.meta
  AI Game Jam/Assets/Materials/New Material.mat
  AI Game Jam/Assets/Materials/New Material.mat.meta
  AI Game Jam/Assets/Scenes/ComplexPuzzle.unity
  AI Game Jam/Assets/Scenes/ComplexPuzzle.unity.meta
  AI Game Jam/Assets/Scripts/CameraFollow.cs
  AI Game Jam/Assets/Scripts/ComplexGoal.cs
  AI Game Jam/Assets/Scripts/ComplexGoal.cs.meta
  AI Game Jam/Assets/Scripts/EnemySpotlight.cs
  AI Game Jam/Assets/Scripts/InvisibleObject.cs
  AI Game Jam/Assets/Scripts/Item.cs
  AI Game Jam/Assets/Scripts/ItemGoal.cs
  AI Game Jam/Assets/Scripts/ParallaxEffect.cs
  AI Game Jam/Assets/Scripts/PlayerInteraction.cs
  AI Game Jam/Assets/Scripts/PlayerMovement.cs
  AI Game Jam/Assets/Scripts/SecurityLight.cs
  AI Game Jam/Assets/Scripts/SecurityLightMovement.cs
Labels: Expanded Feature
